# Paths to TMS9900 compilation tools 
# ( Set in environment to override paths )
#TMS9900_DIR?=/home/tursilion/gcc9900/bin
TMS9900_DIR?=/home/tursi/newtms9900-gcc/newgcc9900/bin
ELF2EA5_DIR?=/home/tursi/gcc9900/bin
EA5_SPLIT_DIR?=/home/tursi/gcc9900/bin
CLASSIC99_DSK1?=/mnt/d/classic99/DSK1/
LIBTI99?=/mnt/d/work/ti/libti99/

# Full paths to the executables used
GAS=$(TMS9900_DIR)/tms9900-as
LD=$(TMS9900_DIR)/tms9900-ld
CC=$(TMS9900_DIR)/tms9900-gcc

CP=/usr/bin/cp
NAME=rick

# Path to elf2cart conversion utility
ELF2CART=/mnt/d/work/ti/Elf2BankedCart/elf2bankedcart

# Flags used during linking
#
# Locate the code (.text section) and the data (.data section)
# a linker script is necessary to define the output sections (that will replace the list in the Coleco CRT0)
# That will also let us set the start addresses. The ELF should in theory contain section names which will let
# out custom cartridge builder figure out where things go.
# https://ftp.gnu.org/old-gnu/Manuals/ld-2.9.1/html_node/ld_19.html
LDFLAGS_EA5=-M -T 

INCPATH=-I/mnt/d/work/libti99ALL -I../../include -I../../../ti/f18a
LIBPATH=-L/mnt/d/work/libti99ALL/buildti
LIBS=-lti99

# Note: no-function-cse prevents gcc from preferring registers for bl calls, "-minline_rtl -fdump-rtl-expand" for rtl in asm and expand
CFLAGS=-Os -std=c99 -c -s --save-temp -DTI99 -fno-builtin -fno-function-cse
#-minline_rtl
.PHONY: all clean base f18a

# crt0 must be first!
OBJECT_LIST = crt0.o vdpint.o control.o dat_ents.o dat_ents2.o dat_maps1.o dat_maps2.o dat_maps3.o dat_maps4.o dat_screens.o  \
    draw.o e_bomb.o e_bonus.o e_box.o e_bullet.o e_rick.o e_sbonus.o e_them.o ents.o env.o fb.o \
    game.o img.o maps.o scr_gameover.o scr_getname.o scr_imain.o scr_imap.o scr_pause.o soundbank.o \
    scroller.o sounds.o sprites.o sysarg.o sysevt.o syskbd.o system.o sysvid.o tiles.o \
    util.o xrick.o scratchpad.o CPlayerCommonHandEdit.o CPlayerTIHandEdit.o CPlayerTIHandlers.o

# the tilemap and title page use the same source files for F18A and 9918A mode - probably shouldn't but they do ;)
OBJECT_LIST_9918A = dat_spritesTI0.o dat_spritesTI1.o dat_spritesTI2.o dat_spritesTI3.o dat_spritesTI4.o \
                    dat_picscTI.o dat_picspTI.o dat_tilescTI.o dat_tilespTI.o
OBJECT_LIST_F18A = sprf0pal.o sprf00.o sprf01.o sprf02.o sprf10.o sprf11.o sprf12.o sprf20.o sprf21.o sprf22.o sprf30.o sprf31.o sprf32.o \
                   sprf40.o sprf41.o sprf42.o splashf18_splitcol1.o splashf18_splitcol2.o splashf18_splitcol3.o splashf18_splitcol4.o \
                   splashf18_splitpat1.o splashf18_splitpat2.o splashf18_splitpat3.o splashf18_splitpat4.o \
                   tilesf18_splitcol1.o tilesf18_splitcol2.o tilesf18_splitcol3.o \
                   tilesf18_splitpat1.o tilesf18_splitpat2.o tilesf18_splitpat3.o dat_hafcTI.o dat_hafpTI.o

# The linker can't handle the fact that the two applications will have many of the same symbols, so we need
# to create two separate applications, and repackage it externally into one. As long as we keep track
# of what is where in each of them, that should be pretty easy.

all: f18a

base:
	-mkdir base
	$(MAKE) -C base -f ../Makefile buildbase

buildbase: $(OBJECT_LIST) $(OBJECT_LIST_9918A)
	$(LD) $(OBJECT_LIST) $(LIBS) $(LIBPATH) $(LDFLAGS_EA5) ../linker_9918.ld -o $(NAME).ea5.elf > ea5base.map
	$(ELF2CART) $(NAME).ea5.elf $(NAME)8.bin

f18a:
	-mkdir f18a
	$(MAKE) -C f18a -f ../Makefile buildf18a

buildf18a: CFLAGS += -DF18A
buildf18a: $(OBJECT_LIST) $(OBJECT_LIST_F18A)
	$(LD) $(OBJECT_LIST) $(LIBS) $(LIBPATH) $(LDFLAGS_EA5) ../linker_f18a.ld -o $(NAME).ea5.elf > ea5f18.map
	$(ELF2CART) $(NAME).ea5.elf $(NAME)8.bin

clean:
	-rm -rf base f18a

# libti99 crt0 copied into folder
crt0.o: ../crt0_bankcart.assembly
	$(GAS) $(AFLAGS) ../crt0_bankcart.assembly -o crt0.o

# other assembly files
%.o: ../%.assembly
	$(GAS) $< -o $@

# Recipe to compile all C files
%.o: ../%.c
	$(CC) -c $< $(CFLAGS) $(INCPATH) -o $@
%.o: ../../../ti/f18a/%.c
	$(CC) -c $< $(CFLAGS) $(INCPATH) -o $@
