/*
 * xrick/src/sprites.c
 *
 * Copyright (C) 1998-2019 bigorno (bigorno@bigorno.net). All rights reserved.
 *
 * The use and distribution terms for this software are contained in the file
 * named README, which can be found in the root of this distribution. By
 * using this software in any fashion, you are agreeing to be bound by the
 * terms of this license.
 *
 * You must not remove this notice, or any other, from this software.
 */



#include "config.h"
#include "env.h"

#include "sprites.h"
#include "fb.h"
#include "maps.h"
#include "tiles.h"
#include "scroller.h"

#include <vdp.h>
#include <string.h>

#ifdef F18A
#define BIN2INC_HEADER_ONLY
#include "sprf00.c"
#include "sprf01.c"
#include "sprf02.c"
#include "sprf10.c"
#include "sprf11.c"
#include "sprf12.c"
#include "sprf20.c"
#include "sprf21.c"
#include "sprf22.c"
#include "sprf30.c"
#include "sprf31.c"
#include "sprf32.c"
#include "sprf40.c"
#include "sprf41.c"
#include "sprf42.c"
#endif

// remapping table for my F18A sprite shuffling - easier to put it here
// and just do one lookup than try to debug all the places sprite indexes are loaded.
// Autogenerated in blassic with:
/*
     10 PRINT "const U8 sprite_index_map[213] = {"
     20 FOR a=0 TO 212
     30 b=a
    100 IF a=32  THEN b=142  : REM bullet right
    110 IF a=33  THEN b=143  : REM bullet left
    120 IF a=41  THEN b=91   : REM crate 1
    130 IF a=42  THEN b=92   : REM crate 2
    140 IF a=43  THEN b=32   : REM tongue statue
    150 IF a=44  THEN b=33   : REM egyptian mask
    160 IF a=45  THEN b=115  : REM rocket
    170 IF a=46  THEN b=47   : REM hostage
    180 IF a=47  THEN b=85   : REM green giant right
    190 IF a=85  THEN b=121  : REM orange brick
    200 IF a=91  THEN b=41   : REM gem
    210 IF a=92  THEN b=42   : REM gem stand
    220 IF a=94  THEN b=111  : REM mummy right 1
    230 IF a=95  THEN b=112  : REM mummy right 2
    240 IF a=109 THEN b=43   : REM bulldog sleep
    250 IF a=110 THEN b=44   : REM bulldog stand
    260 IF a=111 THEN b=45   : REM bulldog run 1
    270 IF a=112 THEN b=46   : REM bulldog run 2
    280 IF a=115 THEN b=95   : REM gunner
    290 IF a=121 THEN b=94   : REM tall spikes
    300 IF a=142 THEN b=150  : REM spear guy right 1
    310 IF a=143 THEN b=151  : REM spear guy right 2
    320 IF a=150 THEN b=109  : REM barrel diag1
    330 IF a=151 THEN b=110  : REM barrel diag2
    400 PRINT b;",";
    410 IF a/16=INT(a/16) THEN PRINT
    420 NEXT a
*/

const U8 sprite_index_map[213] = {
    0,
    1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,
    17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,142,
    143,34,35,36,37,38,39,40,91,92,32,33,115,47,85,48,
    49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,
    65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,
    81,82,83,84,121,86,87,88,89,90,41,42,93,111,112,96,
    97,98,99,100,101,102,103,104,105,106,107,108,43,44,45,46,
    113,114,95,116,117,118,119,120,94,122,123,124,125,126,127,128,
    129,130,131,132,133,134,135,136,137,138,139,140,141,150,151,144,
    145,146,147,148,149,109,110,152,153,154,155,156,157,158,159,160,
    161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,
    177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,
    193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,
    209,210,211,212
};

/*
 * sprites_paint
 *
 * paints sprite <spriteNumber> at the position indicated by <x>, <y>.
 * <x>, <y> are fb-coordinates.
 * simple paint: no clipping, no depth management, nothing.
 */

// there are four hardware sprites for every entity (ENTSNUM is 12, so this totals 52. Four bytes each makes 208)
// TODO: why is it +1?
// CAREFUL here - this *4 represents four sprites per entity, a sprite is 4 bytes (sprite_data_t)
sprite_data_t sprite_table[(ENT_ENTSNUM+1)*4];

// There are up to 12 sprites in game (though our hardware supports 8). We'll let
// the copy function sort that out though.
// This is only called directly by the preview screen
void sprites_paint(U16 spriteNumber, U16 spriteIndex, U16 x, U16 y, U16 load_pattern)
{
    unsigned int nOldBank;
#ifdef F18A
    spriteNumber = sprite_index_map[spriteNumber];
    unsigned int spritePage = spriteNumber / 48;    // sprite page to read from
    unsigned int spriteIdx = spriteNumber % 48;     // Index on a page, not to confuse with spriteIndex, which is psuedo hardware
    unsigned char pal = 4+(spritePage*2);
    // Palettes are indexed in sets of 4 colors, and we want color 16 as the first, so that's palette 4
    if (pal > 10) pal = 8;   // deliberate remap to page 2, not clipping (4,6,8,10,8)
#endif

    // we just have to load the four sprites into the sprite table, and maybe also the pattern
    // (48*4 is only 192 characters, so all psuedo sprites are fine with a dedicated pattern)
    // TODO: need a mapping table for colors
    U8 chr = (U8)(spriteIndex*4);   // work around compiler bug - if we put this inline with the .ch (note: compiler bug is now fixed)
                    // there's also a weird inefficiency, it will use @1(r5) for sprite_table[i].x, but recalculates for .ch 
                    // instead of just doing @2(r5)
    U8* pSpriteTab = &sprite_table[spriteIndex].y;  // y is first entry in the struct
        
    *(pSpriteTab++) = (U8)y;
    *(pSpriteTab++) = (U8)x;
    *(pSpriteTab++) = chr;
#ifdef F18A
    *(pSpriteTab++) = pal;
#else
    *(pSpriteTab++) = COLOR_WHITE;  // TODO: color table
#endif

    *(pSpriteTab++) = (U8)(y+16);
    *(pSpriteTab++) = (U8)x;
    *(pSpriteTab++) = chr+4;
#ifdef F18A
    *(pSpriteTab++) = pal;
#else
    *(pSpriteTab++) = COLOR_WHITE;  // TODO: color table
#endif

    *(pSpriteTab++) = (U8)y;
    *(pSpriteTab++) = (U8)(x+16);
    *(pSpriteTab++) = chr+8;
#ifdef F18A
    *(pSpriteTab++) = pal;
#else
    *(pSpriteTab++) = COLOR_WHITE;  // TODO: color table
#endif

    *(pSpriteTab++) = (U8)y+16;
    *(pSpriteTab++) = (U8)x+16;
    *(pSpriteTab++) = chr+12;
#ifdef F18A
    *(pSpriteTab++) = pal;
#else
    *(pSpriteTab++) = COLOR_WHITE;  // TODO: color table
#endif

    if (load_pattern) {
#ifdef CLASSIC99
        // to figure out how many entities we actually need (I got 10)
        static int largestIndex = 0;
        if (spriteIndex > largestIndex) largestIndex = spriteIndex;
#endif

        VDP_INT_DISABLE;
        // based on which pattern we need, we need to map and copy from ROM
        // each table has 48 of those big objects (8x6)
        nOldBank = nBank;
        // since calculated, we do the bank here manually. SINCE WE DO NOT
        // UPDATE nBank YOU CAN NOT BRANCH TO ANY CODE THAT MIGHT BANK SWITCH AGAIN
#ifndef F18A
        unsigned int spritePage = spriteNumber / 48;    // sprite page to read from
        unsigned int spriteIdx = spriteNumber % 48;     // Index on a page, not to confuse with spriteIndex, which is psuedo hardware
#endif
        // in the math below:
        // spriteIdx is the 128 byte object index on the Rick side
        // i is the starting 32 byte sprite tile index on the TI side (multiple of four, see above)
        // Since sprites are only 21 rows tall, not 32, we can save a few bytes of copy. To make it
        // simple we only do two memcpys (not four, cause of setup overhead), copying 53 bytes instead 
        // of 64 for each left and right half

#ifdef F18A

#ifndef CLASSIC99
        // we copy the sprite in two split parts since there is lots of empty space at
        // the bottom - this saves us some trouble.
        // TODO: Possible future: cache all of Ricks sprites in VDP and use the GPU to load them

        // Note: first page is page 16 (0x6020), covers bit 0. Subsequent tables are 5 pages later.
        SWITCH_IN_BANK((0x6020 + (spritePage*2)));
        vdpmemcpy2(gSpritePat+(spriteIndex*4*8), spriteIdx*128+sprf00, 54);
        vdpmemcpy2(gSpritePat+(spriteIndex*4*8)+64, spriteIdx*128+sprf00+64, 54);

        // second bit
        SWITCH_IN_BANK((0x6020 + ((spritePage+5)*2)));
        vdpmemcpy2(gSpritePat+0x800+(spriteIndex*4*8), spriteIdx*128+sprf00, 54);
        vdpmemcpy2(gSpritePat+0x800+(spriteIndex*4*8)+64, spriteIdx*128+sprf00+64, 54);

        // third bit
        SWITCH_IN_BANK((0x6020 + ((spritePage+10)*2)));
        vdpmemcpy2(gSpritePat+0x1000+(spriteIndex*4*8), spriteIdx*128+sprf00, 54);
        vdpmemcpy2(gSpritePat+0x1000+(spriteIndex*4*8)+64, spriteIdx*128+sprf00+64, 54);
#else

        // Classic99 build doesn't really have banks to switch!
        switch(spritePage) {
            case 0:
                vdpmemcpy(gSpritePat+(spriteIndex*4*8), spriteIdx*128+sprf00, 128); 
                vdpmemcpy(gSpritePat+0x800+(spriteIndex*4*8), spriteIdx*128+sprf01, 128); 
                vdpmemcpy(gSpritePat+0x1000+(spriteIndex*4*8), spriteIdx*128+sprf02, 128); 
                break;
            case 1:
                vdpmemcpy(gSpritePat+(spriteIndex*4*8), spriteIdx*128+sprf10, 128); 
                vdpmemcpy(gSpritePat+0x800+(spriteIndex*4*8), spriteIdx*128+sprf11, 128); 
                vdpmemcpy(gSpritePat+0x1000+(spriteIndex*4*8), spriteIdx*128+sprf12, 128); 
                break;
            case 2:
                vdpmemcpy(gSpritePat+(spriteIndex*4*8), spriteIdx*128+sprf20, 128); 
                vdpmemcpy(gSpritePat+0x800+(spriteIndex*4*8), spriteIdx*128+sprf21, 128); 
                vdpmemcpy(gSpritePat+0x1000+(spriteIndex*4*8), spriteIdx*128+sprf22, 128); 
                break;
            case 3:
                vdpmemcpy(gSpritePat+(spriteIndex*4*8), spriteIdx*128+sprf30, 128); 
                vdpmemcpy(gSpritePat+0x800+(spriteIndex*4*8), spriteIdx*128+sprf31, 128); 
                vdpmemcpy(gSpritePat+0x1000+(spriteIndex*4*8), spriteIdx*128+sprf32, 128); 
                break;
            case 4:
                vdpmemcpy(gSpritePat+(spriteIndex*4*8), spriteIdx*128+sprf40, 128); 
                vdpmemcpy(gSpritePat+0x800+(spriteIndex*4*8), spriteIdx*128+sprf41, 128); 
                vdpmemcpy(gSpritePat+0x1000+(spriteIndex*4*8), spriteIdx*128+sprf42, 128); 
                break;
        }
#endif

#else
        // Note: page index 0x6006 is determined by dat_sprintesTI0.o in the linker file
        SWITCH_IN_BANK((0x6006 + (spritePage*2)));

#ifndef CLASSIC99
        vdpmemcpy2(gSpritePat+(spriteIndex*4*8), spriteIdx*128+sprites_data0, 54);
        vdpmemcpy2(gSpritePat+(spriteIndex*4*8)+64, spriteIdx*128+sprites_data0+64, 54);
#else
        // Classic99 build doesn't have banks to switch!
        switch(spritePage) {
            case 0:
                vdpmemcpy(gSpritePat+(spriteIndex*4*8), spriteIdx*128+sprites_data0, 128); break;
            case 1:
                vdpmemcpy(gSpritePat+(spriteIndex*4*8), spriteIdx*128+sprites_data1, 128); break;
            case 2:
                vdpmemcpy(gSpritePat+(spriteIndex*4*8), spriteIdx*128+sprites_data2, 128); break;
            case 3:
                vdpmemcpy(gSpritePat+(spriteIndex*4*8), spriteIdx*128+sprites_data3, 128); break;
            case 4:
                vdpmemcpy(gSpritePat+(spriteIndex*4*8), spriteIdx*128+sprites_data4, 128); break;
        }
#endif

#endif
        // restore the previous page
        SWITCH_IN_BANK(nOldBank);

        VDP_INT_ENABLE;
    }
}

void sprites_clear() {
    // once we have sprite indexes hard assigned to entities, we don't need to
    // call this function every frame, which is causing flicker
    memset(sprite_table, 0xd1, sizeof(sprite_table));
    // might as well deassign the entity sprites too
    for (int i=0; i<ENT_ENTSNUM + 1; ++i) {
        ent_ents[i].spriteIndex = 0xff;
    }
}

/*
 * sprites_paint2
 *
 * paints sprite <spriteNumber> at the position indicated by <x>, <y>.
 * <x>, <y> are map-coordinates, they are aligned to tile columns.
 * <front> when true indicates that the sprite must not be behind anything.
 * complex paint: manages highlight, depth.
 */
// still not doing 'front' management, but we can clip
void sprites_paint2(U16 entityNumber) {
	U16 x_map, y_map;
	U16 x_fb, y_fb;
	const U16 width = 0x20, height = 0x15;

    if (env_highlight) {
        if (ent_ents[entityNumber].sprite == 0) {
            // for highlight, just load one of the explosion sprites
            ent_ents[entityNumber].sprite = 36;
        }
    }

	/* get map/px */
	x_map = ent_ents[entityNumber].x;
	y_map = ent_ents[entityNumber].y;

	/* clip */
	if (maps_clip(x_map, y_map, width, height)) {  /* return if not visible */
        // make sure sprite is offscren
        if (ent_ents[entityNumber].spriteIndex != 0xff) {
            // clip all four sprites
            sprite_table[ent_ents[entityNumber].spriteIndex].y = 0xd2;  // 0xd2 so it does not get re-assigned to someone else!
            sprite_table[ent_ents[entityNumber].spriteIndex+1].y = 0xd2;
            sprite_table[ent_ents[entityNumber].spriteIndex+2].y = 0xd2;
            sprite_table[ent_ents[entityNumber].spriteIndex+3].y = 0xd2;
        }
		return;
    }

    /* assign a sprite index if necessary */
    if (ent_ents[entityNumber].spriteIndex == 0xff) {
        for (unsigned int i=0; i<(ENT_ENTSNUM+1)*4; i+=4) {
            if (sprite_table[i].y == 0xd1) {
                ent_ents[entityNumber].spriteIndex = i;
                break;
            }
        }
    }

	/* convert to fb/px */
	x_fb = x_map + MAPS_FB_X + 32;  // fix offset
	y_fb = y_map - MAPS_FB_Y; // fix offset

    sprites_paint(ent_ents[entityNumber].sprite,        // pattern to draw
                  ent_ents[entityNumber].spriteIndex,   // pseudo sprite index
                  x_fb, y_fb,                           // location
                  ent_ents[entityNumber].lastSpriteDrawn != ent_ents[entityNumber].sprite); // whether the pattern needs reloading
    
    ent_ents[entityNumber].lastSpriteDrawn = ent_ents[entityNumber].sprite;
}

/* eof */